// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Id       int64  `json:"id"`
	OpenId   string `josn:"open_id"`
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Role     int64  `json:"role"`
	Rolename string `json:"role_name"`
	Avatar   string `json:"avatar"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	UserName string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type RegisterResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
	Role         int64  `json:"role"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
	Role         int64  `json:"role"`
}

type WXMiniAuthReq struct {
	Code          string `json:"code"`
	IV            string `json:"iv"`
	EncryptedData string `json:"encrypted_data"`
}

type WXMiniAuthResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	UserInfo User `json:"user_info"`
}

type GetAllApplicantReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetAllApplicantResp struct {
	List []User `json:"list"`
}

type UploadAvatarReq struct {
}

type UploadAvatarResp struct {
	Url string `json:"url"`
}

type ImportExcelReq struct {
}

type ImportExcelResp struct {
	List []User `json:"list"`
}

type EditUserInfoReq struct {
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Email    string `json:"email"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
}

type EditUserInfoResp struct {
}

type RoleChangeInfo struct {
	Id           int64  `json:"id"`
	CreateTime   string `json:"createtime"`    // 变动身份时间
	UserId       int64  `json:"user_id"`       // 身份变动用户Id
	UserName     string `json:"username"`      // 身份变动用户名称
	OperatorId   int64  `json:"operator_id"`   // 操作人
	OperetorName string `json:"operator_name"` // 操作人姓名
	NewRole      int64  `json:"new_role"`      // 新身份代号 '0-申请队员 1-岗前培训 2-见习队员 3-正式队员 4-督导老师 30-普通队员 31-核心队员 32-区域负责人 33-组委会成员 34-组委会主任'
	NewRoleName  string `json:"new_role_name"` // 新身份名称
	OldRole      int64  `json:"old_role"`      // 旧身份代号
	OldRoleName  string `json:"old_role_name"` // 旧身份名称
}

type RoleChangeInfoListReq struct {
	UserId int64 `json:"user_id"`
}

type RoleChangeInfoListResp struct {
	List []RoleChangeInfo `json:"list"`
}

type ChangeRoleReq struct {
	UserId  int64 `json:"user_id"`
	NewRole int64 `json:"new_role"`
}

type ChangeRoleResp struct {
	CreateTime  string `json:"createtime"`    // 变动身份时间
	NewRole     int64  `json:"new_role"`      // 新身份代号 '0-申请队员 1-岗前培训 2-见习队员 3-正式队员 4-督导老师 30-普通队员 31-核心队员 32-区域负责人 33-组委会成员 34-组委会主任'
	NewRoleName string `json:"new_role_name"` // 新身份名称
	OldRole     int64  `json:"old_role"`      // 旧身份代号
	OldRoleName string `json:"old_role_name"` // 旧身份名称
}

type RescueInfo struct {
	Id                int64  `json:"id"`
	WeiboAccount      string `json:"weibo_account"`
	Area              string `json:"area"`
	Sex               string `json:"sex"`
	Age               string `json:"age"`
	ReleaseTime       string `json:"release_time"`
	MainDemand        string `json:"main_demand"`
	RiskLevel         string `json:"risk_level"`
	Status            int    `json:"status"`
	RescueTeacherId   int    `json:"rescue_teacher_id"`
	RescueTeacherName string `json:"rescue_teacher_name"`
}

type AuthReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type AuthResp struct {
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type PushReq struct {
	WeiboAccount string `json:"weibo_account"`
	Area         string `json:"area"`
	Sex          string `json:"sex"`
	Age          string `json:"age"`
	ReleaseTime  string `json:"release_time"`
	MainDemand   string `json:"main_demand"`
	RiskLevel    string `json:"risk_level"`
}

type PushResp struct {
}

type PushWithStatusReq struct {
	WeiboAccount string `json:"weibo_account"`
	Area         string `json:"area"`
	Sex          string `json:"sex"`
	Age          string `json:"age"`
	ReleaseTime  string `json:"release_time"`
	MainDemand   string `json:"main_demand"`
	RiskLevel    string `json:"risk_level"`
	Status       int    `json:"status"`
}

type PushWithStatusResp struct {
}

type DestroyTokenReq struct {
}

type DestroyTokenResp struct {
}

type GetRescueInfoReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetRescueInfoResp struct {
	List []RescueInfo `json:"rescue_info"`
}

type GetRescueInfoByAreaReq struct {
	Page     int64  `json:"page"`
	PageSize int64  `json:"page_size"`
	Area     string `json:"area"`
}

type GetRescueInfoByAreaResp struct {
	List []RescueInfo `json:"rescue_info"`
}

type ApplicationForm struct {
	Id            int64  `json:"id"`
	CreateTime    string `json:"create_time"`
	UpdateTime    string `json:"upadate_time"`
	UserId        int64  `json:"user_id"`
	Mobile        string `json:"mobile"`
	Username      string `json:"username"`
	Sex           int64  `json:"sex"`
	Address       string `json:"address"`
	Birthday      string `json:"birthday"`
	Email         string `json:"email"`
	Status        int64  `json:"status"`
	Operator_id   int64  `json:"operator_id"`
	Operator_name string `json:"operator_name"`
}

type ApplicationFormReq struct {
}

type ApplicationFormResp struct {
	Form ApplicationForm `json:"application_form"`
}

type ApplicationFormsReq struct {
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type ApplicationFormsResp struct {
	List []ApplicationForm `json:"list"`
}

type ProcessReq struct {
	ApplicationFormId int64 `json:"application_form_id"`
	Status            int64 `json:"status"`
}

type ProcessResp struct {
	CreateTime string `json:"createtime"`
}

type GetByStatusReq struct {
	Status   int64 `json:"status"`
	Page     int64 `json:"page"`
	PageSize int64 `json:"page_size"`
}

type GetByStatusResp struct {
	List []ApplicationForm `json:"list"`
}

type EditReq struct {
	Mobile   string `json:"mobile"`
	Username string `json:"username"`
	Sex      int64  `json:"sex"`
	Address  string `json:"address"`
	Birthday string `json:"birthday"`
	Email    string `json:"email"`
}

type EditResp struct {
}
